### ISSUE TITLE
导入的 Excel 数据集点击报错

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#27]
上传的 Excel 数据集，再次点击报错，该 Excel 为阿里云分销平台导出的账单文件。
![image](https://user-images.githubusercontent.com/48945409/123393148-63403c00-d5d0-11eb-9aed-0ead823cfa02.png)

**Comment by wangzhen-fit2cloud** [comment]
doris-fe 容器是不是没有正常运行

**Comment by luyang351** [comment]
是运行的
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/48945409/123410202-9fc86380-d5e1-11eb-8122-fd3913205e68.png">

**Comment by fitchibing** [comment]
我也有一个点击报错 报错信息还不一样
Failed to extract data: io.dataease.exception.DataEaseException: java.sql.SQLSyntaxErrorException: errCode = 2, detailMessage = Duplicate column name 'C_fac54c3430528339ac075d688db27ce8' at io.dataease.exception.DataEaseException.throwException(DataEaseException.java:22) at io.dataease.datasource.provider.JdbcProvider.exec(JdbcProvider.java:54) at io.dataease.service.dataset.ExtractDataService.createDorisTable(ExtractDataService.java:359) at io.dataease.service.dataset.ExtractDataService.extractData(ExtractDataService.java:191) at io.dataease.service.dataset.DataSetTableService.lambda$save$0(DataSetTableService.java:115) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) Caused by: java.sql.SQLSyntaxErrorException: errCode = 2, detailMessage = Duplicate column name 'C_fac54c3430528339ac075d688db27ce8' at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:762) at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:646) at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:1006) at io.dataease.datasource.provider.JdbcProvider.exec(JdbcProvider.java:51) ... 10 more

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们尽快修复。

**Comment by sunyukun8888** [comment]
Failed to extract data: io.dataease.exception.DataEaseException: java.sql.SQLException: Access denied for user 'root' (using password: YES)

**Comment by xuwei-fit2cloud** [comment]
v1.1.1 已修复
